export interface ProductItem {
  id: string;
  name: string;
  slug: string;
  category: "rings" | "necklaces" | "earrings" | "bracelets" | "bangles" | "pendants";
  categoryId: string;
  sellingPrice: number;
  mrp: number;
  discount: number;
  metalType: string;
  metalPurity: string;
  stock: number;
  sku: string;
  shortDescription: string;
  description: string;
  images: Array<{ imageUrl: string; altText?: string }>;
  featured?: boolean;
  bestSeller?: boolean;
  newArrival?: boolean;
  rating: number;
  reviewCount: number;
  variants: Array<{ id: string; ringSize?: string; inStock: boolean }>;
}

export const MOCK_PRODUCTS: ProductItem[] = [
  // ── RINGS ──
  {
    id: "1",
    name: "Eternal Solitaire Ring",
    slug: "eternal-solitaire-ring",
    category: "rings",
    categoryId: "rings",
    sellingPrice: 125000,
    mrp: 145000,
    discount: 13.8,
    metalType: "Yellow Gold",
    metalPurity: "18K (750)",
    stock: 5,
    sku: "JWL-RNG-001",
    shortDescription: "A brilliant-cut diamond solitaire seated upon an 18K handcrafted yellow gold band.",
    description: "The Eternal Solitaire Ring encapsulates timeless romance and unrivaled brilliance. Centered around a hand-selected conflict-free diamond, set within an intricate micro-claw setting of 18K solid yellow gold. Each facet is calibrated for maximum light dispersion and fire.",
    images: [
      { imageUrl: "/images/hero-ring.jpg", altText: "Eternal Solitaire Ring Front View" },
      { imageUrl: "/images/products/ring-set.jpg", altText: "Eternal Solitaire Ring Side Detail" },
      { imageUrl: "/images/hero-ring.jpg", altText: "Ring in Luxury Box" },
    ],
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 48,
    variants: [
      { id: "v-10", ringSize: "10", inStock: true },
      { id: "v-12", ringSize: "12", inStock: true },
      { id: "v-14", ringSize: "14", inStock: true },
      { id: "v-16", ringSize: "16", inStock: true },
      { id: "v-18", ringSize: "18", inStock: true },
    ],
  },
  {
    id: "5",
    name: "Trinity Pavé Stacking Bands",
    slug: "trinity-stacking-rings",
    category: "rings",
    categoryId: "rings",
    sellingPrice: 78000,
    mrp: 92000,
    discount: 15.2,
    metalType: "Rose & Yellow Gold",
    metalPurity: "18K (750)",
    stock: 12,
    sku: "JWL-RNG-005",
    shortDescription: "Trio of slender pavé diamond bands designed to interlock in harmonic luxury.",
    description: "Designed for modern versatile elegance, the Trinity Stacking Bands feature one high-polish band, one pavé diamond eternity band, and one accented center stone ring.",
    images: [
      { imageUrl: "/images/products/ring-set.jpg", altText: "Trinity Stacking Rings" },
      { imageUrl: "/images/hero-ring.jpg", altText: "Stacking Detail" },
    ],
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.7,
    reviewCount: 41,
    variants: [
      { id: "v-10", ringSize: "10", inStock: true },
      { id: "v-12", ringSize: "12", inStock: true },
      { id: "v-14", ringSize: "14", inStock: true },
    ],
  },
  {
    id: "7",
    name: "Maharani 22K Antique Polki Ring",
    slug: "maharani-antique-polki-ring",
    category: "rings",
    categoryId: "rings",
    sellingPrice: 95000,
    mrp: 110000,
    discount: 13.6,
    metalType: "Yellow Gold",
    metalPurity: "22K (916)",
    stock: 4,
    sku: "JWL-RNG-007",
    shortDescription: "Opulent 22K yellow gold statement ring set with uncut polki diamonds and fine meenakari.",
    description: "Handcrafted by traditional karigars, this 22K solid gold heirloom ring features uncut polki stones set in pure gold bezels with intricate floral engraving on the reverse.",
    images: [
      { imageUrl: "/images/hero-ring.jpg", altText: "Maharani 22K Antique Polki Ring" },
      { imageUrl: "/images/products/ring-set.jpg", altText: "Polki Ring Side Detail" },
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.9,
    reviewCount: 22,
    variants: [
      { id: "v-12", ringSize: "12", inStock: true },
      { id: "v-14", ringSize: "14", inStock: true },
      { id: "v-16", ringSize: "16", inStock: true },
    ],
  },
  {
    id: "8",
    name: "Aura Solitaire Diamond Ring",
    slug: "aura-solitaire-diamond-ring",
    category: "rings",
    categoryId: "rings",
    sellingPrice: 235000,
    mrp: 260000,
    discount: 9.6,
    metalType: "White Gold",
    metalPurity: "18K (750)",
    stock: 3,
    sku: "JWL-RNG-008",
    shortDescription: "Oval cut solitary diamond encircled with an ethereal French-pave halo.",
    description: "A show-stopping 1.5-carat center solitaire embraced by a halo of micro-pave diamonds. Hand-finished in luminous 18K white gold for captivating fire and brilliance.",
    images: [
      { imageUrl: "/images/hero-ring.jpg", altText: "Aura Solitaire Diamond Ring" },
      { imageUrl: "/images/products/ring-set.jpg", altText: "Ring Angled Shot" },
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 5.0,
    reviewCount: 16,
    variants: [
      { id: "v-10", ringSize: "10", inStock: true },
      { id: "v-12", ringSize: "12", inStock: true },
      { id: "v-14", ringSize: "14", inStock: true },
    ],
  },
  {
    id: "9",
    name: "Regal 22K Floral Filigree Band",
    slug: "regal-22k-filigree-band",
    category: "rings",
    categoryId: "rings",
    sellingPrice: 62000,
    mrp: 72000,
    discount: 13.9,
    metalType: "Yellow Gold",
    metalPurity: "22K (916)",
    stock: 7,
    sku: "JWL-RNG-009",
    shortDescription: "Delicate openwork 22K yellow gold band inspired by royal Rajasthani architecture.",
    description: "A testament to master goldsmithing, this 22K yellow gold ring features ornate scroll filigree with beaded milgrain edges. Hallmarked 916 purity for everyday regal charm.",
    images: [
      { imageUrl: "/images/products/ring-set.jpg", altText: "Regal 22K Floral Filigree Band" },
      { imageUrl: "/images/hero-ring.jpg", altText: "Band View" },
    ],
    featured: false,
    bestSeller: true,
    newArrival: false,
    rating: 4.8,
    reviewCount: 38,
    variants: [
      { id: "v-12", ringSize: "12", inStock: true },
      { id: "v-14", ringSize: "14", inStock: true },
      { id: "v-16", ringSize: "16", inStock: true },
    ],
  },

  // ── NECKLACES ──
  {
    id: "2",
    name: "Royal Filigree Choker Necklace",
    slug: "royal-filigree-necklace",
    category: "necklaces",
    categoryId: "necklaces",
    sellingPrice: 285000,
    mrp: 320000,
    discount: 10.9,
    metalType: "Yellow Gold",
    metalPurity: "22K (916)",
    stock: 3,
    sku: "JWL-NCK-002",
    shortDescription: "Regal handcrafted 22K gold lace choker adorned with brilliant marquise cut diamonds.",
    description: "Inspired by ancient royal courts, the Royal Filigree Choker is an architectural triumph of master goldsmithing. Over 80 hours of hand-woven gold filigree cascade gently across the collarbone, highlighted by shimmering brilliant-cut diamond teardrops.",
    images: [
      { imageUrl: "/images/products/necklace.jpg", altText: "Royal Filigree Necklace" },
      { imageUrl: "/images/products/necklace.jpg", altText: "Necklace Close-up Filigree" },
    ],
    featured: true,
    bestSeller: true,
    newArrival: true,
    rating: 5.0,
    reviewCount: 32,
    variants: [{ id: "v-std", inStock: true }],
  },
  {
    id: "10",
    name: "Rivière Solitaire Diamond Necklace",
    slug: "riviere-solitaire-necklace",
    category: "necklaces",
    categoryId: "necklaces",
    sellingPrice: 340000,
    mrp: 380000,
    discount: 10.5,
    metalType: "Yellow Gold",
    metalPurity: "18K (750)",
    stock: 2,
    sku: "JWL-NCK-010",
    shortDescription: "Continuous strand of graduated brilliant-cut solitaires set in 18K yellow gold.",
    description: "The epitome of high jewellery elegance. Each diamond is calibrated for ideal proportion, creating an unbroken ribbon of pure radiance.",
    images: [
      { imageUrl: "/images/products/necklace.jpg", altText: "Rivière Solitaire Diamond Necklace" },
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.9,
    reviewCount: 14,
    variants: [{ id: "v-std", inStock: true }],
  },

  // ── EARRINGS ──
  {
    id: "3",
    name: "Cascade Diamond Chandelier Earrings",
    slug: "cascade-diamond-earrings",
    category: "earrings",
    categoryId: "earrings",
    sellingPrice: 98000,
    mrp: 115000,
    discount: 14.7,
    metalType: "Yellow Gold",
    metalPurity: "18K (750)",
    stock: 8,
    sku: "JWL-ERR-003",
    shortDescription: "Dramatic cascading drop earrings lined with pear and baguette cut diamonds.",
    description: "Articulated for graceful movement, the Cascade Diamond Earrings catch ambient light with every turn of the head. Featuring alternating baguettes and brilliant pear cuts set in lustrous 18K yellow gold prongs.",
    images: [
      { imageUrl: "/images/products/earrings.jpg", altText: "Cascade Diamond Earrings" },
      { imageUrl: "/images/products/earrings.jpg", altText: "Earrings Detail" },
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.8,
    reviewCount: 19,
    variants: [{ id: "v-std", inStock: true }],
  },
  {
    id: "11",
    name: "Lumière Solitaire Diamond Studs",
    slug: "lumiere-solitaire-diamond-studs",
    category: "earrings",
    categoryId: "earrings",
    sellingPrice: 115000,
    mrp: 130000,
    discount: 11.5,
    metalType: "Yellow Gold",
    metalPurity: "18K (750)",
    stock: 6,
    sku: "JWL-ERR-011",
    shortDescription: "Classic 4-prong diamond solitaire studs set in 18K solid yellow gold.",
    description: "A cornerstone of fine jewellery collections. Features perfectly matched brilliant-cut diamonds with screw-back closures for ultimate security.",
    images: [
      { imageUrl: "/images/products/earrings.jpg", altText: "Lumière Solitaire Diamond Studs" },
    ],
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 5.0,
    reviewCount: 42,
    variants: [{ id: "v-std", inStock: true }],
  },
  {
    id: "12",
    name: "Kundan Jadau 22K Gold Jhumkas",
    slug: "kundan-jadau-22k-jhumkas",
    category: "earrings",
    categoryId: "earrings",
    sellingPrice: 155000,
    mrp: 175000,
    discount: 11.4,
    metalType: "Yellow Gold",
    metalPurity: "22K (916)",
    stock: 4,
    sku: "JWL-ERR-012",
    shortDescription: "Royal 22K yellow gold jhumkas with uncut gemstones and seed pearl tassels.",
    description: "Mastercrafted with centuries-old Jadau techniques, these 22K solid gold jhumkas showcase heritage aesthetics, ruby accents, and lustrous basra pearl drops.",
    images: [
      { imageUrl: "/images/products/earrings.jpg", altText: "Kundan Jadau 22K Gold Jhumkas" },
    ],
    featured: false,
    bestSeller: true,
    newArrival: true,
    rating: 4.9,
    reviewCount: 29,
    variants: [{ id: "v-std", inStock: true }],
  },

  // ── BRACELETS & BANGLES ──
  {
    id: "4",
    name: "Heritage Engraved Gold Bangle",
    slug: "heritage-gold-bangle",
    category: "bracelets",
    categoryId: "bracelets",
    sellingPrice: 165000,
    mrp: 190000,
    discount: 13.1,
    metalType: "Yellow Gold",
    metalPurity: "22K (916)",
    stock: 4,
    sku: "JWL-BNG-004",
    shortDescription: "Hand-engraved floral motif openable bangle with diamond cluster centerpiece.",
    description: "Carrying forward centuries of ancestral jewelry heritage, this 22K solid gold bangle exhibits hand-chiseled floral filigree accented by a radiant cluster of natural diamonds at its clasp.",
    images: [
      { imageUrl: "/images/products/bracelet.jpg", altText: "Heritage Gold Bangle" },
      { imageUrl: "/images/products/bracelet.jpg", altText: "Bangle Side Engravings" },
    ],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.9,
    reviewCount: 27,
    variants: [{ id: "v-2-4", inStock: true }, { id: "v-2-6", inStock: true }],
  },
  {
    id: "13",
    name: "Diamond Mirage Pavé Tennis Bracelet",
    slug: "diamond-mirage-tennis-bracelet",
    category: "bracelets",
    categoryId: "bracelets",
    sellingPrice: 210000,
    mrp: 240000,
    discount: 12.5,
    metalType: "Yellow Gold",
    metalPurity: "18K (750)",
    stock: 5,
    sku: "JWL-BRC-013",
    shortDescription: "Flexible 18K gold bracelet encrusted with continuous handset diamond solitaires.",
    description: "A fluid line of fiery diamonds set into custom 18K yellow gold four-prong baskets with a double security clasp.",
    images: [
      { imageUrl: "/images/products/bracelet.jpg", altText: "Diamond Mirage Pavé Tennis Bracelet" },
    ],
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 31,
    variants: [{ id: "v-7", inStock: true }],
  },

  // ── PENDANTS ──
  {
    id: "6",
    name: "Imperial Diamond Drop Pendant",
    slug: "celestial-drop-necklace",
    category: "pendants",
    categoryId: "pendants",
    sellingPrice: 148000,
    mrp: 172000,
    discount: 13.9,
    metalType: "Yellow Gold",
    metalPurity: "18K (750)",
    stock: 6,
    sku: "JWL-PND-006",
    shortDescription: "A pear-shaped solitaires drop pendant strung upon an Italian gold box chain.",
    description: "An understated statement of pure poise. The Celestial Drop Pendant floats gracefully, suspended from a delicate diamond-cut Italian box chain crafted in 18K yellow gold.",
    images: [
      { imageUrl: "/images/products/necklace.jpg", altText: "Imperial Diamond Pendant" },
    ],
    featured: true,
    bestSeller: true,
    newArrival: false,
    rating: 4.9,
    reviewCount: 35,
    variants: [{ id: "v-std", inStock: true }],
  },
];
